apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: dev
  labels:
    app: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: ghcr.io/marwan-ghonem/gitops-demo/gitops-demo:85453f6b585328cb14f2a8d035a9ab1b280a1236
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: APP_VERSION
              value: "v1.0.0"
            - name: ENVIRONMENT
              value: "development"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
