apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-marwan
  namespace: argocd
spec:
  project: default
  
  # Source - your Git repository
  source:
     repoURL: https://github.com/marwan-ghonem/gitops-demo.git
    targetRevision: main
    path: k8s
  
  # Destination - your dev cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true        # Delete resources removed from Git
      selfHeal: true     # Revert manual changes
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences for certain fields
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Allow manual scaling
